### ISSUE TITLE
Cambiar código

### ISSUE THREAD

**Issue by vcuspinera** [EduardoSanchezZ/Clase-07-09-22#3]
Hola Eduardo,
Ya revisé tu repositorio y tengo dos comentarios:

1.  No se ve el GIF, al parecer es porque estás poniendo la liga de la página y no a la del GIF, pero para poder desplegarlo puedes utilizar la siguiente liga que te comparto:

> La liga que actualmente tienes es: https://giphy.com/clips/uefa-euro-cup-2020-uefa-RNlgWpfnRNRGBES99r. 
> La liga que te recomiendo usar es: https://media.giphy.com/media/WzPVwbTNBIBQDjdpeV/giphy-downsized.gif

2. Por cuestión de presentación, también recomendaría que al final del texto, en donde compartiste la "Fuente" pusieras un texto con hipervínculo y no directamente la página, para lo cual deberías usar el formato `[NOMBRE DE LA FUENTE](http://www.pagina_de_internet.com)`

Considerando los comentarios anteriores, tu código completo debería quedar de la siguiente manera:

```
# Clase-07-09-22 #Hello, World
Este repositorio es donde estaré subiendo mis scripts de python sobre temas de mi interés 

![](https://media.giphy.com/media/WzPVwbTNBIBQDjdpeV/giphy-downsized.gif)

Fuente: [GIPHY, Euro Cup Football GIF By UEFA](https://media.giphy.com/media/WzPVwbTNBIBQDjdpeV/giphy-downsized.gif)
```

Saludos,
Víctor

**Comment by EduardoSanchezZ** [comment]
Modificaciones hechas, actividad completada.
